### PR TITLE
Added set of messages to support Glonass and combined GNS

### PR DESCRIPTION
**Pull request by GrzegorzBlok**
* Added support for GNSS Fix Data message (GNS).
* GSA, RMC and GGA messages extended to support GLONASS and GNS (combined systems).

List of new messages supported:
GPGNS, GLGNS, GNGNS, GLGSA, GNGSA, GNGGA, GLGGA, GNRMC, GLRMC.

It allows to use data from combined satellite navigation systems - currently GPS + GLONASS.

### CODE REVIEW

**Comment by dotMorten** [comment]
@GrzegorzBlok This is an amazing piece of work. Thank you very much. However it also introduces a significant amount of breaking changes, so would want to ponder a little bit over this first. Perhaps we could move it into a separate branch first, and I can meddle some with it.

**Comment by GrzegorzBlok** [comment]
@dotMorten Sure, branch might be a good idea. I'm not sure if I'm able to move it into a separate branch.
Just one note -  all implementations that I made are backward compatible, so any existing code should work with my this without requiring any change.

**Comment by GrzegorzBlok** [comment]
Hi Morten, are you still interested in the pull request? Do you want me to do anything about this to allow it to be merged?

**Comment by dotMorten** [comment]
We have to redo the PR. When you create it, you need to pick a different branch than the master branch to push it to.

**Comment by dotMorten** [comment]
I've created  a dev branch you can do the PR to. 
You're right code is backward compatible, but there are still breaking API changes since you changed the inheritance hiararchy, and also if you look at the changes in one of the unit test, that change was made because a breaking change for one of the enums who's namespace change.

**Pull request closed without merging**
