### PR TITLE
Added set of messages to support Glonass and combined GNS

### PR DESCRIPTION
**Pull request by GrzegorzBlok**
- Added support for GNSS Fix Data message family (GNS).
- GSA, RMC and GGA messages extended to support GLONASS and GNS (combined systems).

List of new messages supported:
GPGNS, GLGNS, GNGNS, GLGSA, GNGSA, GNGGA, GLGGA, GNRMC, GLRMC.

It allows to use data from combined satellite navigation systems - currently GPS + GLONASS.

Note: this is follow up to this closed pull request: https://github.com/dotMorten/NmeaParser/pull/11
@dotMorten : I updated my changes, so the pull request is up to date. I also reverted the namespace change in UTs - it wasn't necessary. Still, you are absolutely right that the inheritance hierarchy is changed and it may have some implications for users that extends the library.

### CODE REVIEW

**Comment by rumdood** [comment]
Is there any word on when this will be integrated into a release? I have a slew of customers rolling out new hardware that all seem to work with the combined systems rather than just US-GPS and it would be nice to be able to utilize the nuget package for this.

In the meantime, we're pulling @GrzegorzBlok's code and using that.

**Comment by dotMorten** [comment]
Sorry I haven't had any time to work on this, and I don't have a Glonass receiver to test this on.

In any case, this PR adds a bunch of breaking changes that means I would have to significantly rework your otherwise awesome work.

The API does however support plugging in custom messages without the need for a new release, and this could be handled that way.

**Comment by terribletim** [comment]
@dotMorten just a query.... isn't this the very nature of collaborative development? The master project is a work of art - a big thanks from all of us. If it's going to continue to grow, then need to take new message types with unit tests on their merit, without expecting you to verify against applicable hardware. This PR contributes a significant amount of new message types as well structured code. Prefixed with "imho", it's worth the breaking change.

**Comment by dotMorten** [comment]
I think this describes it pretty good: http://tirania.org/blog/archive/2010/Dec-31.html

Don't get me wrong I love what you're adding. But I would prefer taking that as a starting point and building it a way that suits the best way I'd like to maintain this library. That's a little tough though, since I don't have the device to really test that my changes works the right way.

Perhaps if you could provide me with an extensive NMEA log file from your device, I could start from there?

**Comment by terribletim** [comment]
@dotMorten I stand corrected! 
Will try and help with log files. Our only GNSS receiver is permanently mobbed away from office. Field Eng leaving today for 2-3 days in field so have asked him to log data if time permits. Failing that, maybe @GrzegorzBlok or @rumdood can supply nmea logs.

**Comment by terribletim** [comment]
@dotMorten @GrzegorzBlok Hemisphere tech support have offered to log supported message types on our behalf. Will be available later this week.

Note the position and heading solutions from Hemisphere GNGSS receivers are technically based on GPS (must always have at least four GPS satellites). The other constellations are used as supplemental data in the solution, but Hemisphere do not support a pure GLONASS solution and therefore do not output GLGNS or GLGGA messages.

**Comment by terribletim** [comment]
@dotMorten Here is approx. 10MB sample (upload limit) from 30MB binary file courtesy of Tech Support at [https://hemispheregnss.com/](url)

It contains GPGGA, GNGNS, GPRMC, GNGSA, GPGNS, GLGNS, and GAGNS sentences. 
but is missing GLGSA, GNGGA, GLGGA, GNRMC, GLRMC sentences referred to at top of this conversation.

[HEMI_3_partial.txt](https://github.com/dotMorten/NmeaParser/files/843354/HEMI_3_partial.txt)

**Comment by dotMorten** [comment]
@terribletim Thanks! that's a great start. 

Just added support in the Desktop sample app to show unknown messages. That's a least a start to try and understand these.

image

Any chance of also getting GLGSA, GNGGA, GLGGA, GNRMC and GLRMC  ?

**Comment by terribletim** [comment]
@dotMorten see my comment above re position and heading solutions... Hemisphere will only output GP***, and they reckon this is industry standard and that any manufacturer outputting GL*** sentences is probably not following the NMEA standard. Regardless, seems @GrzegorzBlok has some hardware that is outputting the GL*** messages, so dependent on him for sample data.

**Comment by GrzegorzBlok** [comment]
@terribletim Since I no longer work on GPS related projects I'm not able to get any more NMEA messages apart those that I used in unit tests.

**Comment by terribletim** [comment]
@dotMorten a small offering of sample messages listed here (GLGSA, GNGGA, GNRMC)[http://docs.mirifica.eu/GlobalTop_Technology/features/Galileo/NMEA%20sentence%20for%20GPS%20GLONASS%20GALILEO.pdf](url)

From what I have seen, difference GLGGA vs GPGGA is talker id only (see brief mention at bottom of [https://hemispheregnss.com/gnssreference/GPGGA.htm](url))

GLRMC is elusive.

**Comment by GrzegorzBlok** [comment]
@terribletim From what I understand the GGA is NMEA message. GP or GL are just talker prefix. So, in other words the GLGGA and GPGGA - or any other NMEA message for that purpose - are the same message. The only difference is the device that it is sent from.

**Comment by terribletim** [comment]
@dotmorten a suggestion for re-factoring @GrzegorzBlok changes in order to integrate GN, GL, and future data types whilst preserving inheritance hierarchy in master branch. I admit it's not perfect, but it may be a way forwards. 

Basic premise is that rather than distinguishing between all different types of navigation systems which means lots of namespaces, just use a generic GNSS (ie industry-wide term global navigation satellite system). Ideally GPS would be included under this, but in order to preserve inheritance we'll need to live with this inconsistency. And also one other where GNS related constants (fix quality etc) are in the root namespace and not in the new GNSS namespace. 

So sketching out namespaces and classes in project NmeaParser.Shared:

**NMEA**
 _Constants_ (new item, containing enums):
- public enum TalkerId (new)
- public enum FixQuality (moved from GPGGA)
- public enum FixType (new)

_Various base classes_  (from this pull request and also future GNS base classes. Technically these would be better in namespace **NMEA.GNSS** but I think having them here will preserve inheritance): hierarchy):_
- GGA
- GSA
- RMC
- GNS
- GNS

**NMEA.GPS**
 _leave existing GPS classes here,_ changing to inherit from base classes and implement OnMessageLoad as done by @GrzegorzBlok. Assuming that no new "using" statements  = preserving inheritance.

**NMEA.GNSS**
_implementation of all new GNSS classes, such as:_
- GNGNS
- GLGNS
- GAGNS
- GNGSA
- GLGSA
- GLGGA
- GNGGA
- GNRMC
- GLRMC

Note: 
- TalkerId  can also be used for other non-GNS sensors, such as classic marine gyro (HEHDT). 
- FixType is introduced to several messages at NMEA revision 2.3 which haven't yet been implemented. We also need to cater for pre-2.3 messages by having value for Absent.

Hoping I haven't missed an obvious reason why this won't work. 

Regards

Tim

**Comment by terribletim** [comment]
Another suggestion to the above conundrum which maintains backwards compatibility, does not require loads more classes, and mitigates inheritance issues:

- The actual name of the class is irrelevant, because we can identify messages from MsgType (eg GPGGA, GNGNS, GPRMC, GNGSA, GPGNS, GLGNS) and TalkerID (GP, GN, GL etc).
- There is no real need to have 1:1 relationship between Message and Class when the only difference is TalkerId.

So:
1. Adopt GrzegorzBlok's **TalkerId**
2. Change NmeaAttribute definition to allow **multiple** attributes (probably also best to disable attribute inheritance).
3. Modify **LoadMessageTypes** accordingly, to loop thru multiple attributes for each class.
4. Add attributes to classes as required. For example, existing class GPGGA would need attributes for GPGGA, GLGGA, GNGGA. 

I have been using this approach in another (non-NMEA) application and it is working quite well.

**Comment by dotMorten** [comment]
Thank you for this, and sorry for letting this sit so long. Also sorry but I ended up with a slightly different approach for adding this, so going to close this.

**Pull request closed without merging**
